### ISSUE TITLE
Redirects without trailing slash don't work

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/redirects#1]
Can we fix this?

**Comment by haroldangenent** [comment]
Yes they do. Visiting `/my-post-name/` does the same as visiting `/my-post-name`. This way, you don't have to fill in every URL twice (with and without trailing slash).

This is standardized to only use trailing slash URLs in the redirects database, with exceptions for URLs with extensions (`index.html`). It allows the redirects table to stay clean (no double URLs, everything has a standardized format) and this slightly improves performance as well.

For most normal websites, this is very doable. Only when you spider thousands of URLs (with and without extensions), this process becomes harder. I have personally never encountered this when using the Redirects plugin so far.

**Comment by sboerrigter** [comment]
So you always have to enter the source URL with trailing slash? 

Whenever I input an URL without trailing slash the redirect doesn't work. Can't we automatically add the trailing slash whenever a user enters a URL without trailing slash?

**Comment by haroldangenent** [comment]
This is because you could have a non-trailingslash URL as a source (for example, an old `.html` file). We could check for extensions, but this would just cause too much code bloat over a small detail. Marking this as `wontfix`.
