### ISSUE TITLE
Table creation key is too long

### ISSUE THREAD

**Issue by luukdv** [trendwerk/redirects#3]
Just installed the plugin, but the `wp_redirects` table wasn't created. After debugging it turned out the key is too long:

`WordPress database error: [Specified key was too long; max key length is 767 bytes]`

When altering `VARCHAR(255)` to 100 for example, it works again. Is this a problem with this specific installation or the plugin?

**Comment by haroldangenent** [comment]
Turned out to be because of `utf8mb4`.
