### ISSUE TITLE
Cannot redirect files that end with .php

### ISSUE THREAD

**Issue by sboerrigter** [trendwerk/redirects#8]
![screen shot 2016-04-22 at 19 09 27](https://cloud.githubusercontent.com/assets/786875/14749098/d0b78d32-08bd-11e6-902a-8bc6fc62860f.png)

**Comment by luukdv** [comment]
This is not an issue with the plugin, but with WordPress itself. The redirection is hooked onto `404_template`, which is not loaded by WP as you can see in the browser (a fallback to the web server's default 404 page).
